version: '3.7'

services:
  skillbox-users-backend-first:
    container_name: skillbox-users-backend-first
    build:
      dockerfile: "./.docker/go/Dockerfile"
      context: ./
      args:
        - PORT=8081
    ports:
      - "8081"
    restart: "always"
    depends_on:
      - skillbox-users-db
    networks:
      - "skillbox-users.network"

  skillbox-users-backend-second:
    container_name: skillbox-users-backend-second
    build:
      dockerfile: "./.docker/go/Dockerfile"
      context: ./
      args:
        - PORT=8082
    ports:
      - "8082"
    restart: "always"
    depends_on:
      - skillbox-users-db
    networks:
      - "skillbox-users.network"

  skillbox-users-db:
    image: postgres:alpine
    container_name: skillbox-users-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api
      - DATABASE_HOST=db
    ports:
      - '5432:5432'
    networks:
      - "skillbox-users.network"

  skillbox-users-proxy:
    container_name: skillbox-users-proxy
    image: nginx:latest
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - skillbox-users-backend-first
      - skillbox-users-backend-second
    ports:
      - "80:80"
    networks:
      - "skillbox-users.network"

networks:
  skillbox-users.network:
    driver: bridge

volumes:
  database_postgres:
